apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: redis-replication-patch.yaml
    target:
      kind: RedisReplication
      name: redis-replication
  - path: redis-sentinel-patch.yaml
    target:
      kind: RedisSentinel
      name: redis-sentinel