- op: replace
  path: /spec/destination/server
  value: https://kubernetes.default.svc
  target:
    kind: Application
    name: redis-operator-application

- op: replace
  path: /spec/destination/namespace
  value: mtm-vtg-uat
  target:
    kind: Application
    name: redis-operator-application