apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtm-vtg-qa-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mtm-vtg-qa-project
  source:
    repoURL: https://github.com/chanjkh/mtm-k8s-manifests
    targetRevision: HEAD
    path: apps/overlays/vtg-qa                # points to the App of Apps overlay
  destination:
    server: https://kubernetes.default.svc    # need update to correct server
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true