- op: replace
  path: /spec/sources/1/path
  value: manifests/redis/overlays/vtg-qa
  target:
    kind: Application
    name: redis-application

- op: replace
  path: /spec/destination/server
  value: https://kubernetes.default.svc    # needs to be updated to correct k8s server
  target:
    kind: Application
    name: redis-application

- op: replace
  path: /spec/destination/namespace
  value: mtm-vtg-qa
  target:
    kind: Application
    name: redis-application

- op: replace
  path: /spec/project
  value: mtm-vtg-qa-project
  target:
    kind: Application
    name: redis-application

- op: replace
  path: /metadata/name
  value: mtm-vtg-qa-redis-application
  target:
    kind: Application
    name: redis-application

- op: replace
  path: /spec/sources/0/helm/releaseName
  value: mtm-vtg-qa-redis-operator
  target:
    kind: Application
    name: redis-application