- op: replace
  path: /spec/destination/server
  value: https://kubernetes.default.svc    # needs to be updated to correct k8s server
  target:
    kind: Application
    name: airflow-application

- op: replace
  path: /spec/destination/namespace
  value: mtm-vtg-uat
  target:
    kind: Application
    name: airflow-application

- op: replace
  path: /spec/project
  value: mtm-vtg-uat-project
  target:
    kind: Application
    name: airflow-application

- op: replace
  path: /metadata/name
  value: mtm-vtg-uat-airflow-application
  target:
    kind: Application
    name: airflow-application