- op: replace
  path: /spec/destination/server
  value: https://kubernetes.default.svc    # needs to be updated to correct k8s server
  target:
    kind: Application
    name: redis-operator-application

- op: replace
  path: /spec/destination/namespace
  value: mtm-vtg-uat
  target:
    kind: Application
    name: redis-operator-application

- op: replace
  path: /spec/project
  value: mtm-vtg-uat-project
  target:
    kind: Application
    name: redis-operator-application

- op: replace
  path: /metadata/name
  value: mtm-vtg-uat-redis-application
  target:
    kind: Application
    name: redis-operator-application

- op: replace
  path: /spec/sources/0/helm/values
  value: |
    installCRDs: true
    serviceAccountName: "mtm-vtg-uat-redis-operator"
    redisOperator:
      name: "mtm-vtg-uat-redis-operator"
  target:
    kind: Application
    name: redis-operator-application