apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mtm-vtg-qa-project
  namespace: argocd
spec:
  description: "Project for MTM VTG QA env"
  sourceRepos:
  - '*'
  destinations:
  - server: https://kubernetes.default.svc    # needs to be updated to correct k8s server
    namespace: argocd
  - server: https://kubernetes.default.svc    # needs to be updated to correct k8s server
    namespace: mtm-vtg-qa
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'