apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mtm-vtg-uat-project
  namespace: argocd
spec:
  description: "Project for MTM VTG UAT env"
  sourceRepos:
  - '*'
  destinations:
  - server: https://kubernetes.default.svc    # need update to correct server
    namespace: argocd
  - server: https://kubernetes.default.svc    # need update to correct server
    namespace: mtm-vtg-uat
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'