apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: redis-operator-application-patch.yaml
    target:
      kind: Application
      name: redis-operator-application
  - patch: |-
      $patch: delete
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: airflow-application
    target:
      kind: Application
      name: airflow-application